points:
  zones:
    matrix:
      anchor:
      #shift to fix placement on KiCAD
        shift: [100, -100]
      columns:
        left:
          key:
            column_net: P031
        pinky:
          key:
            column_net: P029
        ring:
          key:
            stagger: 5
            column_net: P002
        middle:
          key:
            stagger: 3
            column_net: P115
        index:
          key:
            stagger: -3
            column_net: P017
        inner:
          key:
            stagger: -3
            column_net: P020
        right:
          key:
            stagger: -4.5
            column_net: P022
      rows:
        bottom:
          key:
            row_net: P100
        home:
          key:
            row_net: P024
        top:
          key:
            row_net: P111
        num:
          key:
            row_net: P113
    thumbfan:
      anchor:
        ref: matrix_middle_bottom
        shift: [-4.5, -23]
      columns:
        left:
          key:
            bind: [3, 4, 0, 0]
            column_net: P115
        home:
          key:
            bind: [3, 1, 0, 0]
            splay: -5
            origin: [-10, -9]
            column_net: P017
        far:
          key:
            bind: [3, 3, 0, 0]
            splay: -5
            origin: [-9.5, -9]
            column_net: P020
        out:
          key:
            splay: -12
            origin: [-10, -9]
            column_net: P022
      rows:
        thumb:
          key:
            row_net: P011
outlines:
  left:
    - where: true
      what: rectangle
      bound: true
      size: [U + 1, U + 1]
      fillet: 1
  leftkeys: 
      - where: true
        what: rectangle
        bound: false
        size: [14, 14]
  leftcutout:
    - name: left
    - operation: subtract
      name: leftkeys
pcbs:
  altair:
    outlines:
      main:
        outline: left
    footprints:
      mx_hotswap:
        what: mx
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: 180
      # Main diodes
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          #move diode above switch
          shift: [0, 4]
      # Controller
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: matrix_left_num
          shift: [9, -1]
      # Battery jack
      jstph:
        what: jstph
        where:
          ref: matrix_middle_top
          shift: [-6, -10.5]
          rotate: 90
        params: 
          side: B
          pos: pos
          neg: GND
      # Reset switch
      horizontal_reset:
        what: EVQPUC
        params:
          side: B
          from: GND
          to: RST
        where: 
          ref: matrix_left_home
          # shift: [0.5U, 0.41U]
          shift: [-0.41U, 0.4U]
          rotate: 90
      # Battery on/off switch
      battery_switch:
        what: slider
        where:
          ref: matrix_left_top
          # shift: [0, 0.42U]
          shift: [-0.42U, 0.225U]
          rotate: 90
        params:
          side: B
          from: pos
          to: RAW
      # Mounting holes M2 screws
      top_left_hole: 
        what: mountinghole
        where:
          ref: matrix_ring_top
          shift: [-0.4U, 0.4U]
      top_right_hole:
        what: mountinghole
        where:
          ref: matrix_index_top
          shift: [0.4U, 0.4U]
      bottom_left_hole:
        what: mountinghole
        where: 
          ref: matrix_left_bottom
          shift: [-0.25U, 0.5U]
      bottom_middle_hole:
        what: mountinghole
        where: 
          ref: matrix_ring_bottom
          shift: [0.5U, -0.5U]
      bottom_right_hole:
        what: mountinghole
        where:
          ref: matrix_right_bottom
          shift: [0.25U, 0.5U]
cases:
  plate:
    - name: leftcutout
      extrude: 1.2